import { createClient } from '@supabase/supabase-js';

const supabaseUrl = 'https://heqkymxvbcekdszrrygx.supabase.co';
const supabaseAnonKey = 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImhlcWt5bXh2YmNla2RzenJyeWd4Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3ODgxMDE2ODIsImV4cCI6MjEwMzY3NzY4Mn0.tZYiZvz2rtkEE0rHBbaVBR8bWlrgPWZ4kupanx2qHI8';

const supabase = createClient(supabaseUrl, supabaseAnonKey);

const SEED_PROFILES = [
  {
    name: 'Alex Chen',
    email: 'alex.chen@campus.edu',
    role: 'STUDENT',
    department: 'Computer Science & Engineering (CSE)',
    year_of_study: '4th Year (Senior)',
    avatar_url: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=150',
    know_points: 2480,
    badges: ['Pioneer', 'Mentor', 'Verified Expert'],
    contributions_count: 14,
    bio: 'Final Year CS Scholar. Placed at Google (SDE-1). Focuses on distributed consensus & systems design.',
  },
  {
    name: 'Dr. Sarah Jenkins',
    email: 's.jenkins@campus.edu',
    role: 'FACULTY',
    department: 'Computer Science & Engineering (CSE)',
    year_of_study: 'Associate Professor',
    avatar_url: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?w=150',
    know_points: 2150,
    badges: ['Pioneer', 'Mentor', 'Verified Expert'],
    contributions_count: 22,
    bio: 'Lead Researcher, Cloud Computing & Distributed Systems Lab.',
  },
  {
    name: 'Marcus Ramirez',
    email: 'm.ramirez@campus.edu',
    role: 'TECHNICIAN',
    department: 'Central Computing & Hardware Labs',
    year_of_study: 'Senior Systems Admin',
    avatar_url: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=150',
    know_points: 1940,
    badges: ['Pioneer', 'Mentor', 'Verified Expert'],
    contributions_count: 19,
    bio: 'Central HPC & AI Supercomputing Lab Lead.',
  },
  {
    name: 'Eleanor Vance',
    email: 'admin.knowpass@campus.edu',
    role: 'ADMIN',
    department: 'Academic IT Infrastructure',
    year_of_study: 'Dean of Academic Computing',
    avatar_url: 'https://images.unsplash.com/photo-1580489944761-15a19d654956?w=150',
    know_points: 1650,
    badges: ['Pioneer', 'Mentor'],
    contributions_count: 12,
    bio: 'Institutional Administrator for KnowPass governance.',
  },
  {
    name: 'Priya Sundaram',
    email: 'priya.s@campus.edu',
    role: 'FACULTY',
    department: 'Electronics & Communication (ECE)',
    year_of_study: 'Assistant Professor',
    avatar_url: 'https://images.unsplash.com/photo-1580894732444-8ecded7900cd?w=150',
    know_points: 1420,
    badges: ['Pioneer', 'Mentor', 'Verified Expert'],
    contributions_count: 11,
    bio: 'VLSI Digital Design & ASIC Verification In-Charge.',
  },
  {
    name: 'Sneha Reddy',
    email: 'sneha.reddy@campus.edu',
    role: 'STUDENT',
    department: 'Electronics & Communication (ECE)',
    year_of_study: '4th Year (Senior)',
    avatar_url: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=150',
    know_points: 1180,
    badges: ['Pioneer', 'Verified Expert'],
    contributions_count: 8,
    bio: 'ECE Core hardware enthusiast. Placed at NVIDIA & Qualcomm.',
  },
  {
    name: 'Vikram Malhotra',
    email: 'vikram.m@campus.edu',
    role: 'STUDENT',
    department: 'Mechanical Engineering (ME)',
    year_of_study: '4th Year (Senior)',
    avatar_url: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=150',
    know_points: 1050,
    badges: ['Pioneer', 'Verified Expert'],
    contributions_count: 7,
    bio: 'Formula Student Racecar Aerodynamics & CAD Lead.',
  },
  {
    name: 'David Kim',
    email: 'david.kim@campus.edu',
    role: 'STUDENT',
    department: 'Computer Science & Engineering (CSE)',
    year_of_study: '3rd Year (Junior)',
    avatar_url: 'https://images.unsplash.com/photo-1522075469751-3a6694fb2f61?w=150',
    know_points: 890,
    badges: ['Verified Expert'],
    contributions_count: 6,
    bio: 'Cloud Infrastructure & Kubernetes Contributor.',
  },
];

const SEED_ENTRIES = [
  {
    title: 'Distributed Consensus: Implementing Raft Algorithm in Go with TLA+ Formal Verification',
    category: 'Project Experience',
    knowledge_type: 'Project Experience',
    department: 'Computer Science & Engineering (CSE)',
    year_of_study: '4th Year (Senior)',
    author_name: 'Alex Chen',
    author_role: 'STUDENT',
    summary: 'Design notes on building an RPC-driven Raft consensus cluster in Go with randomized election timers and TLA+ model checking to avoid split-brain split votes.',
    content: `# Distributed Consensus in Go with Raft\n\n### 📌 Architecture Overview\nImplemented a 5-node cluster supporting leader election, log replication, and safe state machine compaction.\n\n### 🛡️ Preventing Split-Brain in Elections\n* Randomized election timeouts between 150ms and 300ms.\n* Strict majority vote (N/2 + 1) required before accepting client writes.`,
    rating: 5.0,
    views: 1840,
    upvotes: 312,
    is_verified: true,
    verified_by: 'Dr. Sarah Jenkins (Faculty Advisor)',
    tags: ['Go', 'Raft', 'Distributed-Systems', 'TLA+', 'Concurrency'],
    status: 'APPROVED',
  },
  {
    title: 'Production RAG AI Pipeline: Hybrid Dense-Sparse Search with ChromaDB & LangChain',
    category: 'Project Experience',
    knowledge_type: 'Project Experience',
    department: 'Computer Science & Engineering (CSE)',
    year_of_study: '3rd Year (Junior)',
    author_name: 'David Kim',
    author_role: 'STUDENT',
    summary: 'Complete engineering guide to building low-latency semantic search using hybrid BM25 lexical matching and dense vector embeddings with cross-encoder re-ranking.',
    content: `# Production Hybrid RAG Pipeline\n\n### 📌 Retrieval Strategy\nCombining dense embeddings with sparse BM25 scores via Reciprocal Rank Fusion (RRF) improved factual recall by 34%.`,
    rating: 4.9,
    views: 1420,
    upvotes: 245,
    is_verified: true,
    verified_by: 'Campus AI Research Group',
    tags: ['RAG', 'Vector-DB', 'ChromaDB', 'Python', 'LLM'],
    status: 'APPROVED',
  },
  {
    title: 'RISC-V 5-Stage Pipelined Core in Verilog with Dynamic Branch Prediction on Artix-7 FPGA',
    category: 'Project Experience',
    knowledge_type: 'Project Experience',
    department: 'Electronics & Communication (ECE)',
    year_of_study: '4th Year (Senior)',
    author_name: 'Sneha Reddy',
    author_role: 'STUDENT',
    summary: 'Hardware implementation of an RV32I 5-stage CPU core featuring forwarding hazard units and 2-bit branch predictors achieving 100MHz Fmax on Xilinx Artix-7.',
    content: `# RISC-V 5-Stage Core on Artix-7\n\n### ⚙️ Hazard Resolution\n* Data forwarding from EX/MEM and MEM/WB stages eliminated 85% of load-use pipeline stalls.`,
    rating: 4.8,
    views: 1190,
    upvotes: 198,
    is_verified: true,
    verified_by: 'Priya Sundaram (ECE Dept)',
    tags: ['RISC-V', 'Verilog', 'FPGA', 'Computer-Architecture', 'Vivado'],
    status: 'APPROVED',
  },
  {
    title: 'Formula Student Chassis Aerodynamics & Boundary Layer CFD Meshing in ANSYS Fluent',
    category: 'Project Experience',
    knowledge_type: 'Project Experience',
    department: 'Mechanical Engineering (ME)',
    year_of_study: '4th Year (Senior)',
    author_name: 'Vikram Malhotra',
    author_role: 'STUDENT',
    summary: 'Aerodynamic optimization of inverted multi-element front wing and rear diffuser, achieving Cl*A of 2.8 at 60 km/h with y+ < 1 prism layer inflation meshes.',
    content: `# FSAE Aerodynamics & CFD Workflow\n\n### 🏎️ Ground Effect Modeling\n* Designed underbody venturi tunnels with polyhedral meshing to capture vortex ground-effect downforce.`,
    rating: 4.9,
    views: 1350,
    upvotes: 210,
    is_verified: true,
    verified_by: 'Faculty Advisor - Formula SAE Team',
    tags: ['CFD', 'Aerodynamics', 'ANSYS-Fluent', 'CAD', 'Formula-Student'],
    status: 'APPROVED',
  },
  {
    title: 'Google & Microsoft SDE-1 Placement Playbook: Concurrency, LLD & Graph DSA',
    category: 'Placement Insight',
    knowledge_type: 'Placement Insight',
    department: 'Computer Science & Engineering (CSE)',
    year_of_study: '4th Year (Senior)',
    author_name: 'Alex Chen',
    author_role: 'STUDENT',
    summary: '5-round interview blueprint with compensation details (₹44.5 LPA), high-frequency graph problems, low-level design patterns, and STAR behavioral answers.',
    content: `# Tier-1 Tech Campus Placement Playbook\n\n### 💼 Round-by-Round Breakdown\n1. OA: 2 Graph Hard + 1 2D DP.\n2. LLD: Thread-safe Parking Lot Rate Limiter.\n3. HLD: Distributed URL Shortener with Redis Cache.`,
    rating: 5.0,
    views: 2650,
    upvotes: 520,
    is_verified: true,
    verified_by: 'Campus Training & Placement Cell',
    tags: ['Placement-Insight', 'SDE', 'Google', 'Microsoft', 'DSA'],
    status: 'APPROVED',
  },
  {
    title: 'NVIDIA & Qualcomm ASIC Hardware Interview Guide: STA Violations & Gray Code CDC',
    category: 'Placement Insight',
    knowledge_type: 'Placement Insight',
    department: 'Electronics & Communication (ECE)',
    year_of_study: '4th Year (Senior)',
    author_name: 'Sneha Reddy',
    author_role: 'STUDENT',
    summary: 'Core semiconductor placement questions: Setup/Hold time slack equations, clock domain crossing (CDC) synchronizers, and Gray-coded asynchronous FIFOs.',
    content: `# Semiconductor ASIC Placement Playbook\n\n### ⚡ High-Frequency Questions\n* Calculating max operating frequency with clock jitter and setup delay.\n* Resolving hold time violations using data-path buffer insertion.`,
    rating: 4.9,
    views: 1780,
    upvotes: 340,
    is_verified: true,
    verified_by: 'Dept of ECE Placement Committee',
    tags: ['Placement-Insight', 'NVIDIA', 'Qualcomm', 'VLSI', 'STA'],
    status: 'APPROVED',
  },
  {
    title: 'HPC Slurm Batch GPU Allocation & Multi-Node PyTorch Distributed Training SOP',
    category: 'Lab Tip',
    knowledge_type: 'Lab Tip',
    department: 'Computer Science & Engineering (CSE)',
    year_of_study: 'All Levels',
    author_name: 'Marcus Ramirez',
    author_role: 'TECHNICIAN',
    summary: 'Standard operating procedure for submitting multi-GPU jobs on the campus 32-node A100 cluster with torch.distributed.launch and scratch disk cleanup.',
    content: `# Campus HPC Cluster SLURM SOP\n\n### 🚀 Submitting Batch Scripts\n\`\`\`bash\n#SBATCH --gres=gpu:a100:2\n#SBATCH --time=08:00:00\nmodule load cuda/12.8 pytorch/2.4\nsrun python train_ddp.py\n\`\`\``,
    rating: 4.9,
    views: 1980,
    upvotes: 380,
    is_verified: true,
    verified_by: 'Prof. Davis (Director of IT)',
    tags: ['HPC', 'SLURM', 'GPU', 'CUDA', 'PyTorch'],
    status: 'APPROVED',
  },
];

async function seed() {
  console.log('--- Seeding Profiles into Supabase PostgreSQL ---');
  const { data: profData, error: profErr } = await supabase.from('profiles').upsert(SEED_PROFILES, { onConflict: 'email' }).select();
  if (profErr) {
    console.error('Error inserting profiles:', profErr);
  } else {
    console.log(`✅ Successfully seeded ${profData.length} profiles!`);
  }

  console.log('--- Seeding Knowledge Entries into Supabase PostgreSQL ---');
  const { data: entryData, error: entryErr } = await supabase.from('knowledge_entries').insert(SEED_ENTRIES).select();
  if (entryErr) {
    console.error('Error inserting knowledge entries:', entryErr);
  } else {
    console.log(`✅ Successfully seeded ${entryData.length} live knowledge entries!`);
  }
}

seed();
